---

name:
    cointracking-imports
version:
    0.1.0.0
github:
    prikhi/cointracking-imports
homepage:
    https://github.com/prikhi/cointracking-imports#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2021 Pavan Rikhi
category:
    Web
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Short, one-line summary of project here.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
when:
    condition:
        impl(ghc >= 8.0)
    then:
        ghc-options:
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
    else:
        ghc-options:
            - -fwarn-incomplete-record-updates
            - -fwarn-incomplete-uni-patterns

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.3 && < 5
    - base-compat-batteries


library:
    source-dirs:
        src
    dependencies:
        []

tests:
    cointracking-imports-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - cointracking-imports
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit