---

name:
    cointracking-imports
version:
    0.1.0.1
github:
    prikhi/cointracking-imports
homepage:
    https://github.com/prikhi/cointracking-imports#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2021 Pavan Rikhi
category:
    Web, Finance
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate CSV & XLSX files for importing into CoinTracking.

description: |
    @cointracking-imports@ is a library for generating CSV & XLSX files to use
    with <https://cointracking.info CoinTracking>'s Import feature. You
    construct a list of @CTImportData@, then feed those to our CSV/XLSX
    generating functions.

    E.g., if you generate a list of your BNB staking rewards, you can use this
    library build a CSV file to import those rewards into CoinTracking.


ghc-options:
    - -Wall
when:
    condition:
        impl(ghc >= 8.0)
    then:
        ghc-options:
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
    else:
        ghc-options:
            - -fwarn-incomplete-record-updates
            - -fwarn-incomplete-uni-patterns

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.3 && < 5
    - base-compat-batteries
    - bytestring < 1
    - cassava < 1
    - filepath >= 1 && < 2
    - lens >= 3.0.4 && < 6
    - scientific < 1
    - text < 2
    - time < 2
    - xlsx < 1


library:
    source-dirs:
        src
    dependencies:
        []

tests:
    cointracking-imports-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - cointracking-imports
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
